/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Frames;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author uribe.markel
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form nhome
     */
    public Home() throws IOException {
        

        initComponents();
        //jLabelImage = new JLabel(new ImageIcon("C:\\Users\\kalboetxeaga.ager\\Downloads\\Boton_Muestra-20210519T060314Z-001\\Abejitas\\Java_App\\src\\PRUEBA.jpg"));

        //setContentPane(new JLabel(new ImageIcon("C:\\Users\\kalboetxeaga.ager\\Downloads\\Boton_Muestra-20210519T060314Z-001\\Abejitas\\Java_App\\src\\Prueba.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new view.frameComponents.Button();
        jLabel1 = new javax.swing.JLabel();
        MEMBERS = new view.frameComponents.Button();
        PAYMENTS = new view.frameComponents.Button();
        INVENTORY = new view.frameComponents.Button();
        COMMENTS = new view.frameComponents.Button();
        AVAILABILITY = new view.frameComponents.Button();
        NOTIFICATIONS = new view.frameComponents.Button();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        members = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();

        button1.setText("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ERLETE Home");
        setBackground(new java.awt.Color(255, 255, 153));
        setForeground(new java.awt.Color(255, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ERLETE");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 779, 55));

        MEMBERS.setBorder(null);
        MEMBERS.setText("MANAGE MEMBERS");
        MEMBERS.setGradientLineColor(new java.awt.Color(255, 0, 255));
        MEMBERS.setLineColor(new java.awt.Color(0, 0, 255));
        MEMBERS.setLinePainted(true);
        MEMBERS.setRounded(true);
        getContentPane().add(MEMBERS, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 163, 169, 29));

        PAYMENTS.setBorder(null);
        PAYMENTS.setText("MANAGE PAYMENTS");
        PAYMENTS.setGradientLineColor(new java.awt.Color(255, 0, 255));
        PAYMENTS.setLineColor(new java.awt.Color(0, 0, 255));
        PAYMENTS.setLinePainted(true);
        PAYMENTS.setRounded(true);
        getContentPane().add(PAYMENTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 219, 169, 29));

        INVENTORY.setBorder(null);
        INVENTORY.setText("MANAGE INVENTORY");
        INVENTORY.setGradientLineColor(new java.awt.Color(255, 0, 255));
        INVENTORY.setLineColor(new java.awt.Color(0, 0, 255));
        INVENTORY.setLinePainted(true);
        INVENTORY.setRounded(true);
        getContentPane().add(INVENTORY, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 161, 169, 29));

        COMMENTS.setBackground(new java.awt.Color(153, 153, 153));
        COMMENTS.setBorder(null);
        COMMENTS.setText("MANAGE COMMENTS");
        COMMENTS.setGradientLineColor(new java.awt.Color(255, 0, 255));
        COMMENTS.setLineColor(new java.awt.Color(0, 0, 255));
        COMMENTS.setLinePainted(true);
        COMMENTS.setRounded(true);
        getContentPane().add(COMMENTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 219, 169, 29));

        AVAILABILITY.setBorder(null);
        AVAILABILITY.setText("MANAGE AVAILABILITY");
        AVAILABILITY.setGradientLineColor(new java.awt.Color(255, 0, 255));
        AVAILABILITY.setLineColor(new java.awt.Color(0, 0, 255));
        AVAILABILITY.setLinePainted(true);
        AVAILABILITY.setRounded(true);
        getContentPane().add(AVAILABILITY, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 163, 169, 29));

        NOTIFICATIONS.setBorder(null);
        NOTIFICATIONS.setText("SEE NOTIFICATIONS");
        NOTIFICATIONS.setGradientLineColor(new java.awt.Color(255, 0, 255));
        NOTIFICATIONS.setLineColor(new java.awt.Color(0, 0, 255));
        NOTIFICATIONS.setLinePainted(true);
        NOTIFICATIONS.setRounded(true);
        getContentPane().add(NOTIFICATIONS, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 219, 169, 29));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MEMBERS:");

        members.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        members.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(members, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(members, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 73, -1, -1));

        jLabelImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\kalboetxeaga.ager\\Downloads\\Boton_Muestra-20210519T060314Z-001\\Abejitas\\Java_App\\src\\PRUEBA.jpg")); // NOI18N
        getContentPane().add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @return
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }
    public static Home createView() throws IOException  {
        Home v = new Home();
        return v;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public view.frameComponents.Button AVAILABILITY;
    public view.frameComponents.Button COMMENTS;
    public view.frameComponents.Button INVENTORY;
    public view.frameComponents.Button MEMBERS;
    public view.frameComponents.Button NOTIFICATIONS;
    public view.frameComponents.Button PAYMENTS;
    private view.frameComponents.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel members;
    // End of variables declaration//GEN-END:variables
}
