/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Frames;
import model.tables.MembersTable;

/**
 *
 * @author uribe.markel
 */
public class Members extends javax.swing.JFrame {

    /**
     * Creates new form nmembers
     */
    public Members() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextFieldPostcode = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();
        jTextFieldAdress = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        memberjTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabelBirthday = new javax.swing.JLabel();
        jTextFieldBirthday = new javax.swing.JTextField();
        jButtonActivate = new view.frameComponents.ButtonInsert();
        jButtonInsertMember = new view.frameComponents.ButtonInsert();
        button1 = new view.frameComponents.Button();
        jButtonDisable = new view.frameComponents.ButtonDelete();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ERLETE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 846, 55));
        getContentPane().add(jTextFieldPostcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 487, 281, -1));
        getContentPane().add(jTextFieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 512, 281, -1));
        getContentPane().add(jTextFieldAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 538, 281, -1));
        getContentPane().add(jTextFieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 564, 138, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Script", 0, 11)); // NOI18N
        jLabel5.setText("MEMBERS:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 87, -1, -1));

        memberjTable.setModel(new MembersTable());
        jScrollPane1.setViewportView(memberjTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 87, -1, 262));

        jLabel6.setFont(new java.awt.Font("Segoe Script", 0, 11)); // NOI18N
        jLabel6.setText("INSERT MEMBERS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 378, -1, -1));

        jLabel7.setText("NAME");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 439, -1, -1));

        jLabel8.setText("SURNAME");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 477, -1, -1));

        jLabel9.setText("EMAIL");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 515, -1, -1));

        jLabel10.setText("PASSWORD");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 438, -1, -1));

        jLabel11.setText("POST CODE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 490, -1, -1));

        jLabel12.setText("CITY");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 515, -1, -1));

        jLabel13.setText("ADRESS");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 541, -1, -1));

        jLabel14.setText("PHONE");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 567, -1, -1));

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 436, 69, -1));
        getContentPane().add(jTextFieldSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 474, 69, -1));
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 512, 69, -1));
        getContentPane().add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 435, 281, -1));

        jLabelBirthday.setText("BIRTHDAY");
        getContentPane().add(jLabelBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 461, 57, -1));

        jTextFieldBirthday.setToolTipText("");
        getContentPane().add(jTextFieldBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 461, 138, -1));

        jButtonActivate.setBorder(null);
        jButtonActivate.setText("ACTIVATE");
        jButtonActivate.setGradientLineColor(java.awt.Color.green);
        jButtonActivate.setLinePainted(true);
        jButtonActivate.setRounded(true);
        getContentPane().add(jButtonActivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 135, 96, 28));

        jButtonInsertMember.setBorder(null);
        jButtonInsertMember.setText("SUBMIT");
        jButtonInsertMember.setGradientLineColor(java.awt.Color.green);
        jButtonInsertMember.setLinePainted(true);
        jButtonInsertMember.setRounded(true);
        getContentPane().add(jButtonInsertMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 543, 96, 28));

        button1.setBorder(null);
        button1.setText("HOME");
        button1.setGradientLineColor(new java.awt.Color(0, 255, 255));
        button1.setLineColor(new java.awt.Color(255, 255, 0));
        button1.setLinePainted(true);
        button1.setRounded(true);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 538, 78, 38));

        jButtonDisable.setBorder(null);
        jButtonDisable.setText("DISABLE");
        jButtonDisable.setGradientLineColor(new java.awt.Color(255, 0, 0));
        jButtonDisable.setLinePainted(true);
        jButtonDisable.setRounded(true);
        getContentPane().add(jButtonDisable, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 169, 96, 26));

        jLabel1.setText("(required:)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 407, -1, -1));

        jLabel2.setText("(optional:)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 403, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("(dd/mm/yyyy)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 464, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\kalboetxeaga.ager\\Downloads\\Boton_Muestra-20210519T060314Z-001\\Abejitas\\Java_App\\src\\PRUEBA.jpg")); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Members().setVisible(true);
//            }
//        });
//    }
        public static Members createMembers() {
        Members v = new Members();
        return v;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.frameComponents.Button button1;
    public view.frameComponents.ButtonInsert jButtonActivate;
    public view.frameComponents.ButtonDelete jButtonDisable;
    public view.frameComponents.ButtonInsert jButtonInsertMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBirthday;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextFieldAdress;
    public javax.swing.JTextField jTextFieldBirthday;
    public javax.swing.JTextField jTextFieldCity;
    public javax.swing.JTextField jTextFieldEmail;
    public javax.swing.JTextField jTextFieldName;
    public javax.swing.JTextField jTextFieldPassword;
    public javax.swing.JTextField jTextFieldPhone;
    public javax.swing.JTextField jTextFieldPostcode;
    public javax.swing.JTextField jTextFieldSurname;
    public javax.swing.JTable memberjTable;
    // End of variables declaration//GEN-END:variables
}
