/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Frames;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
import model.tables.PaymentsTable;
/**
 *
 * @author uribe.markel
 */
public class Payments extends javax.swing.JFrame {

    /**
     * Creates new form npayments
     */
    public Payments() {
        initComponents();
        this.jTablePayments.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer) this.jTablePayments.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
        this.jTablePayments.setGridColor(Color.WHITE);
        this.jTablePayments.setForeground(Color.WHITE);
        this.jScrollPane2.setBackground(new Color(0,0,0,0));
        this.jScrollPane2.setOpaque(false);
        this.jTablePayments.setOpaque(false);
            ((DefaultTableCellRenderer) this.jTablePayments.getDefaultRenderer(Object.class)).setOpaque(false);
        this.jScrollPane2.getViewport().setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePayments = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldPDescription = new javax.swing.JTextField();
        jTextFieldPTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jButtonReset = new view.frameComponents.Button();
        jButtonSearch = new view.frameComponents.Button();
        jButtonPay = new view.frameComponents.ButtonInsert();
        button1 = new view.frameComponents.Button();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAYMENTS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 1006, 55));

        jLabel11.setFont(new java.awt.Font("Segoe Script", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PAYMENTS:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 155, -1, -1));

        jTablePayments.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jTablePayments.setModel(new PaymentsTable());
        jScrollPane2.setViewportView(jTablePayments);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 155, -1, 265));

        jLabel12.setFont(new java.awt.Font("Segoe Script", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ADD PAYMENT:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Description of the payment:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("total:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, -1));

        jTextFieldPDescription.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldPDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 206, 124, -1));

        jTextFieldPTotal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldPTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 232, 124, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FILTER BY MEMBER ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 283, 185, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter a member ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, -1, -1));

        jTextFieldID.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 329, 144, -1));

        jButtonReset.setBorder(null);
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("RESET");
        jButtonReset.setGradientLineColor(java.awt.Color.cyan);
        jButtonReset.setLineColor(java.awt.Color.magenta);
        jButtonReset.setLinePainted(true);
        jButtonReset.setRounded(true);
        getContentPane().add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 367, 63, 24));

        jButtonSearch.setBorder(null);
        jButtonSearch.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearch.setText("SEARCH");
        jButtonSearch.setGradientLineColor(java.awt.Color.magenta);
        jButtonSearch.setLineColor(java.awt.Color.cyan);
        jButtonSearch.setLinePainted(true);
        jButtonSearch.setRounded(true);
        getContentPane().add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 367, 63, 24));

        jButtonPay.setBorder(null);
        jButtonPay.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPay.setText("PAY");
        jButtonPay.setGradientLineColor(new java.awt.Color(0, 255, 0));
        jButtonPay.setLinePainted(true);
        jButtonPay.setRounded(true);
        getContentPane().add(jButtonPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 214, 53, 26));

        button1.setBorder(null);
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("HOME");
        button1.setGradientLineColor(new java.awt.Color(0, 255, 255));
        button1.setLineColor(new java.awt.Color(255, 255, 0));
        button1.setLinePainted(true);
        button1.setRounded(true);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(932, 426, 64, 23));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panal3_.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 1010, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Payments().setVisible(true);
//            }
//        });
//    }
public static Payments createPayments() {
        Payments v = new Payments();
        return v;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.frameComponents.Button button1;
    public view.frameComponents.ButtonInsert jButtonPay;
    public view.frameComponents.Button jButtonReset;
    public view.frameComponents.Button jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTablePayments;
    public javax.swing.JTextField jTextFieldID;
    public javax.swing.JTextField jTextFieldPDescription;
    public javax.swing.JTextField jTextFieldPTotal;
    // End of variables declaration//GEN-END:variables
}
